SERPER_API_URL = "https://google.serper.dev/search"
SERPER_API_KEY = "5f596409b1ddd9b5d0b82022c5544681b97f84ef"
OPENAI_API_KEY = "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"
DB_URI = "mongodb+srv://Rithik:8Characters@cookiebytes.8ahocyp.mongodb.net"
